### ISSUE TITLE
Add extension to the Marketplace

### ISSUE THREAD

**Issue by laurentlb** [google/reflow-list#1]
I haven't seen this extension on https://marketplace.visualstudio.com/ - is there any reason not to add it?

**Comment by garyholt** [comment]
The only reason was I couldn't figure out how to do it.  I tried to do it,
but I'm not the owner so the marketplace wouldn't let me, and I don't even
know whom to ask.  So I gave up.

I'd *like* to add it to the marketplace, I just wasn't going to spend hours
figuring out how.

**Comment by sethvargo** [comment]
Hey @garyholt 

To publish to the marketplace, you'd:

1. `npm install -g @vscode/vsce`
2. `vsce package`

    This will create a vsxi which you could publish as a GitHub release.
    
3. `vsce publish`

    This will publish to the Marketplace. There's an internal doc that explains how to use the Google publisher ID. Ping me on chat, and I'll send over the link.

**Comment by gauravkghildiyal** [comment]
Would love to have this listed in Marketplace for use.

**Comment by chriswillmorris** [comment]
+1.

**Comment by garyholt** [comment]
I think I have figured out how to request a microsoft account that's linked to the google publisher (thanks, sethvargo!).  Once they've set it up, I can try to upload the extension.

**Comment by garyholt** [comment]
I believe this is now available, if I have done everything right: https://marketplace.visualstudio.com/items?itemName=Google.reflowlist

**Comment by gauravkghildiyal** [comment]
I can confirm it's working. Thanks a lot!

**Comment by sethvargo** [comment]
Thanks Gary!
